"use client";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "./../assets/fontawesome-free-6.4.2-web/css/all.min.css";
import "./globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
