"use client";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { Suspense } from "react";
import "./../assets/fontawesome-free-6.4.2-web/css/all.min.css";
import "./globals.css";
import HeaderLoading from "./headerLoading";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={<HeaderLoading />}>
          <Header />
        </Suspense>
        {children}
        <Footer />
      </body>
    </html>
  );
}
